### ISSUE TITLE
Humble support

### ISSUE THREAD

**Issue by YBachmann** [FlexBE/flexbe_webui#1]
Hey, 
in the Readme it states that _"it will not work with older versions such as galactic or humble of the flexbe_behavior_engine"_. 
Are there any plans for a humble version in the future?
Thanks :)

**Comment by dcconner** [comment]
The binary versions of Humble end with version 2.3.5.
I do not plan to back port the webui to the version 2.3.5 API.

There is a change to messaging to improve synchronization of rapidly changing states and especially concurrent states in version 3.0.1 for Iron, Rolling, and ros2-devel branches. 

If you grab one of those branches and build from source then you should be OK in Humble.

**Comment by YBachmann** [comment]
Thanks for the information. 
When I come around to try it out I will let you know if it worked.
