### ISSUE TITLE
Listing new states visualization messes up UI

### ISSUE THREAD

**Issue by RPRKLR** [FlexBE/flexbe_webui#4]
When using the `StateMachine Editor` tab, if I press the `Add state` button and attempt to fill out the "Name" and "Filter" text fields, pressing the `Tab` key multiple times by accident causes the UI to become messed up. Although the UI eventually fixes itself after additional `Tab` key presses, the interface remains navigable between pages even while it's in the messed-up state.

## Steps to Reproduce

1. Navigate to the `StateMachine Editor` tab.
2. Press the `Add state` button.
3. Attempt to fill out the "Name" and "Filter" text fields.
4. Press the `Tab` key multiple times rapidly.

![Screenshot from 2024-06-21 08-00-33](https://github.com/FlexBE/flexbe_webui/assets/83779344/82b10d89-192a-4c13-9c0d-2b7ae58f0dec)

![Screenshot from 2024-06-21 08-01-26](https://github.com/FlexBE/flexbe_webui/assets/83779344/516e8370-ec12-4578-8e1a-2079aaaafdd0)

**Comment by dcconner** [comment]
That one was a surprise, but  I can confirm repeatable on my end.

Lower priority fix for now as it does seem to reset itself with a few additional TABs.

**Comment by dcconner** [comment]
The `beta-enhanced` branch should address this issue.

**Comment by RPRKLR** [comment]
Yes, the new version solves the issue, thanks!
